# Generated by Django 3.2 on 2021-07-19 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Date_Added', models.DateField(default=datetime.datetime.now)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
    ]
